# #[░▒▓](#a3aed2)\
# format = """
# [  ](bg:#a3aed2 fg:#090c0c)\
# [](bg:#769ff0 fg:#a3aed2)\
# $directory\
# [](fg:#769ff0 bg:#394260)\
# $git_branch\
# $git_status\
# [](fg:#394260 bg:#212736)\
# $nodejs\
# $rust\
# $golang\
# $php\
# [](fg:#212736 bg:#1d2230)\
# $time\
# [ ](fg:#1d2230)\
# $line_break\
# $character"""

# [directory]
#     format            = "[ $path ]($style)"
#     style             = "fg:#e3e5e5 bg:#769ff0"
#     truncation_length = 3
#     truncation_symbol = "…/"

#     [directory.substitutions]
#         "Documents" = "󰈙 "
#         "Downloads" = " "
#         "Music"     = " "
#         "Pictures"  = " "

# [git_branch]
#     format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'
#     style  = "bg:#394260"
#     symbol = ""

# [git_status]
#     format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'
#     style  = "bg:#394260"

# [nodejs]
#     format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
#     style  = "bg:#212736"
#     symbol = ""

# [rust]
#     format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
#     style  = "bg:#212736"
#     symbol = ""

# [golang]
#     format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
#     style  = "bg:#212736"
#     symbol = ""

# [php]
#     format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
#     style  = "bg:#212736"
#     symbol = ""

# [time]
#     disabled    = false
#     format      = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
#     style       = "bg:#1d2230"
#     time_format = "%R"                                           # Hour:Minute Format

# [aws]
#     symbol = "  "

# [buf]
#     symbol = " "

# [c]
#     symbol = " "

# [conda]
#     symbol = " "

# [crystal]
#     symbol = " "

# [dart]
#     symbol = " "

# [directory]
#     read_only = " 󰌾"

# [docker_context]
#     symbol = " "

# [elixir]
#     symbol = " "

# [elm]
#     symbol = " "

# [fennel]
#     symbol = " "

# [fossil_branch]
#     symbol = " "

# [git_branch]
#     symbol = " "

# [golang]
#     symbol = " "

# [guix_shell]
#     symbol = " "

# [haskell]
#     symbol = " "

# [haxe]
#     symbol = " "

# [hg_branch]
#     symbol = " "

# [hostname]
#     ssh_symbol = " "

# [java]
#     symbol = " "

# [julia]
#     symbol = " "

# [kotlin]
#     symbol = " "

# [lua]
#     symbol = " "

# [memory_usage]
#     symbol = "󰍛 "

# [meson]
#     symbol = "󰔷 "

# [nim]
#     symbol = "󰆥 "

# [nix_shell]
#     symbol = " "

# [nodejs]
#     symbol = " "

# [ocaml]
#     symbol = " "

# [os.symbols]
#     Alpaquita        = " "
#     Alpine           = " "
#     Amazon           = " "
#     Android          = " "
#     Arch             = " "
#     Artix            = " "
#     CentOS           = " "
#     Debian           = " "
#     DragonFly        = " "
#     Emscripten       = " "
#     EndeavourOS      = " "
#     Fedora           = " "
#     FreeBSD          = " "
#     Garuda           = "󰛓 "
#     Gentoo           = " "
#     HardenedBSD      = "󰞌 "
#     Illumos          = "󰈸 "
#     Linux            = " "
#     Mabox            = " "
#     Macos            = " "
#     Manjaro          = " "
#     Mariner          = " "
#     MidnightBSD      = " "
#     Mint             = " "
#     NetBSD           = " "
#     NixOS            = " "
#     OpenBSD          = "󰈺 "
#     OracleLinux      = "󰌷 "
#     Pop              = " "
#     Raspbian         = " "
#     RedHatEnterprise = " "
#     Redhat           = " "
#     Redox            = "󰀘 "
#     SUSE             = " "
#     Solus            = "󰠳 "
#     Ubuntu           = " "
#     Unknown          = " "
#     Windows          = "󰍲 "
#     openSUSE         = " "

# [package]
#     symbol = "󰏗 "

# [perl]
#     symbol = " "

# [php]
#     symbol = " "

# [pijul_channel]
#     symbol = " "

# [python]
#     symbol = " "

# [rlang]
#     symbol = "󰟔 "

# [ruby]
#     symbol = " "

# [rust]
#     symbol = " "

# [scala]
#     symbol = " "

# [swift]
#     symbol = " "

# [zig]
#     symbol = " "
format = """
$cmd_duration\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$username\
$sudo\
$character\
"""

right_format = """
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$jobs\
$status\
$os\
$container\
$battery\
$time\
"""

add_newline = true

[character]
    error_symbol   = "[⊘](italic purple)"
    format         = "$symbol "
    success_symbol = "[◉](bold italic bright-yellow)"

[env_var.VIMSHELL] # vim subshell
    format = "[$env_value]($style)"
    style  = 'green italic'

[sudo]
    disabled = false
    format   = "[$symbol]($style)"
    style    = "italic bright-purple"
    symbol   = "◇┈"

[username]
    disabled   = false
    format     = "[$user]($style) ▻ "
    style_root = "purple bold italic"
    style_user = "yellow bold"

[directory]
    format            = ' [$path]($style)[$read_only]($read_only_style)'
    home_symbol       = "⌂"
    read_only         = " ■"
    style             = "italic blue"
    truncation_length = 2
    truncation_symbol = "▦ "

[cmd_duration]
    format   = "[$duration ](italic bright-yellow)"
    min_time = 500

[jobs]
    format = "[ $symbol$number]($style)"
    style  = "white"
    symbol = "[▶ ](blue italic)"

[localip]
    disabled = false
    format   = " ◯[$localipv4](bold magenta)"
    ssh_only = true

[time]
    disabled        = false
    format          = "[ $time]($style)"
    style           = "dimmed white"
    time_format     = "%R"
    utc_time_offset = "local"

[battery]
    charging_symbol    = "[↑](italic green)"
    discharging_symbol = "[↓](italic)"
    empty_symbol       = "[▃](italic red)"
    format             = "[ $percentage $symbol]($style)"
    full_symbol        = "[█](italic green)"
    unknown_symbol     = "[░](italic)"

    [[battery.display]]
        style     = "dimmed yellow"
        threshold = 88

    [[battery.display]]
        style     = "dimmed white"
        threshold = 80

[git_branch]
    format = "[ $symbol $branch(:$remote_branch)]($style)"
    style  = "bold italic bright-blue"
    symbol = "[◬](bold bright-blue)"

[git_status]
    ahead      = "[▲│[${count}](bold white)│](italic green)"
    behind     = "[▽│[${count}](bold white)│](italic red)"
    conflicted = "[◪◦](italic bright-magenta)"
    deleted    = "[✕](italic red)"
    diverged   = "[◇ ▲┤[${ahead_count}](regular white)│▽┤[${behind_count}](regular white)│](italic bright-magenta)"
    format     = """([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"""
    modified   = "[●◦](italic yellow)"
    renamed    = "[◎◦](italic bright-blue)"
    staged     = "[■┤[$count](bold white)│](italic bright-cyan)"
    stashed    = "[◦◫◦](italic white)"
    style      = "italic bright-blue"
    untracked  = "[◌◦](italic bright-yellow)"

[deno]
    format         = " deno [∫ $version](blue italic)"
    version_format = "${major}.${minor}"

[lua]
    format = " lua [${symbol}${version}]($style)"
    style  = "italic bright-yellow"
    symbol = "⨀ "

[nodejs]
    detect_files   = ["package-lock.json", "yarn.lock"]
    format         = " node [◫ ($version)](italic bright-green)"
    version_format = "${major}.${minor}"

[python]
    format         = " py [${symbol}${version}]($style)"
    style          = "italic bright-yellow"
    symbol         = "[⌉](italic bright-blue)⌊ "
    version_format = "${major}.${minor}"

[ruby]
    format         = " rb [${symbol}${version}]($style)"
    style          = "italic red"
    symbol         = "◆ "
    version_format = "${major}.${minor}"

[rust]
    format         = " rs [$symbol$version]($style)"
    style          = "italic red"
    symbol         = "⊃ "
    version_format = "${major}.${minor}"

[package]
    format         = " pkg [$symbol$version]($style)"
    style          = "bright-yellow italic"
    symbol         = "◫ "
    version_format = "${major}.${minor}"

[swift]
    format         = " sw [${symbol}${version}]($style)"
    style          = "italic bright-red"
    symbol         = "◁ "
    version_format = "${major}.${minor}"

[aws]
    format = " aws [$symbol $profile $region]($style)"
    style  = "italic blue"
    symbol = "▲ "

[buf]
    format = " buf [$symbol $version $buf_version]($style)"
    symbol = "■ "

[c]
    format = " c [$symbol($version(-$name))]($style)"
    symbol = "∁ "

[conda]
    format = " conda [$symbol$environment]($style)"
    symbol = "◯ "

[dart]
    format = " dart [$symbol($version )]($style)"
    symbol = "◁◅ "

[docker_context]
    format = " docker [$symbol$context]($style)"
    symbol = "◧ "

[elixir]
    format = " exs [$symbol $version OTP $otp_version ]($style)"
    symbol = "△ "

[elm]
    format = " elm [$symbol($version )]($style)"
    symbol = "◩ "

[golang]
    format = " go [$symbol($version )]($style)"
    symbol = "∩ "

[haskell]
    format = " hs [$symbol($version )]($style)"
    symbol = "❯λ "

[java]
    format = " java [${symbol}(${version} )]($style)"
    symbol = "∪ "

[julia]
    format = " jl [$symbol($version )]($style)"
    symbol = "◎ "

[memory_usage]
    format = " mem [${ram}( ${swap})]($style)"
    symbol = "▪▫▪ "

[nim]
    format = " nim [$symbol($version )]($style)"
    symbol = "▴▲▴ "

[nix_shell]
    format = " nix [$symbol$state $name]($style)"
    symbol = "⊛ "

[spack]
    format = " spack [$symbol$environment]($style)"
    symbol = "◇ "
